### ISSUE TITLE
'bootstrap/less/bootstrap.less' wasn't found

### ISSUE THREAD

**Issue by stevepm** [toadkicker/railsstrap#30]
Hi, I installed the gem doing the following:

Added the gem to my gemfile
ran `bundle install`
ran `rails g railsstrap:install`
ran `rails g railsstrap:layout`

And I changed my root path to go to the index of one of my resources that I just scaffolded.

I get the following error: 

`
ctionView::Template::Error ('bootstrap/less/bootstrap.less' wasn't found
  (in /Users/stevenmagelowitz/rails/address_rating/app/assets/stylesheets/bootstrap_and_overrides.css.less)):
     7:     <title><%= content_for?(:title) ? yield(:title) : "AddressRating" %></title>
     8:     <%= csrf_meta_tags %>
     9:
    10:     <%= stylesheet_link_tag "application", :media => "all" %>
    11:
    12:     
    13:     
  app/views/layouts/application.html.erb:10:in `_app_views_layouts_application_html_erb__2531099821453408702_70197828894940'
`

Any idea why this might be happening?

**Comment by toadkicker** [comment]
@stevepm did the initializer solve the issue for you? If so please close the ticket, or I will close it on Jan 17th if I don't hear back from you.

**Comment by prufrock123** [comment]
I'm encountering this same issue.

**Comment by toadkicker** [comment]
I just updated teststrap yesterday, https://github.com/toadkicker/teststrap.. If you can either look through there and see what is different or post a link to your repo and I'll take a peek.

**Comment by prufrock123** [comment]
Sure thing! Thanks so much. I'll reply to you with it shortly.

**Comment by prufrock123** [comment]
The repo is https://github.com/prufrock123/ShawnMovieManager

**Comment by toadkicker** [comment]
I think the first thing is to not include [bootstrap-sass](https://github.com/prufrock123/ShawnMovieManager/blob/master/Gemfile#L26). railsstrap provides bootstrap for you. You use this gem if you want to use LESS instead of SASS, and want the conveniences of html helpers, etc. 

I noticed you're missing [config/initializers/assets.rb](https://github.com/toadkicker/teststrap/blob/master/config/initializers/assets.rb). That could be a bug in the installer.

**Comment by prufrock123** [comment]
ah ok, I had added bootstrap-sass when I was going to use a workaround after I had encountered this bug. I'll remove it now.

I think you're right. I added the 
```
Rails.application.config.assets.precompile += %w(.svg .eot .woff .ttf)
```
to the production env. when I should have created an assets.rb file for the rails 4 app. sorry! let me try that out.

Thanks again. I'll let you know how it goes.

**Comment by Loordo** [comment]
Also consider adding 
`gem 'less-rails'` to `Gemfile`

I have this in mine after something I read on the Wiki though I can't find it to save myself now...

**Comment by toadkicker** [comment]
Should probably go here -> https://github.com/toadkicker/railsstrap/wiki/Installing-using-LESS

**Comment by prufrock123** [comment]
ha! That worked. Thanks so much guys. I guess that was sorta obvious.  I've been full-time JS the last few months so I'm still dusting off my RoR skills. 

Thanks!

**Comment by Loordo** [comment]
Specifically which part worked (just so if people look at the issue)?

Glad its working :+1:

**Comment by prufrock123** [comment]
@Loordo
It all started working once I added
```
gem 'less-rails'
```
to the gemfile like you suggested.

**Comment by Loordo** [comment]
OK cool! Thanks @prufrock123

**Comment by toadkicker** [comment]
Updated the readme to include less-rails in the gemfile
