### ISSUE TITLE
FontAwesome

### ISSUE THREAD

**Issue by Loordo** [toadkicker/railsstrap#31]
Hey mate,

Unsure how to get FontAwesome working for this. Any ideas?

Checked the wiki page and it was just gibberish thus far.

Cheers!

Edit: Using gem version 3.3.1 eb7baf2 on rails 4.1.5

**Comment by toadkicker** [comment]
You do have to do rake asset:precompile to include fontawesome's fonts.

**Comment by toadkicker** [comment]
https://github.com/toadkicker/railsstrap/wiki/FontAwesome

**Comment by Loordo** [comment]
OK so using the installer `bundle exec rails g railsstrap:install` did not automatically add the things on that wiki page.

Manually added:
`Rails.application.config.assets.precompile += %w( fontawesome/fonts/fontawesome-webfont.eot fontawesome/fonts/fontawesome-webfont.woff fontawesome/fonts/fontawesome-webfont.ttf fontawesome/fonts/fontawesome-webfont.svg )` to `config/initializers/assets.rb` 

and 
`@import 'fontawesome'` to `bootstrap_and_overrides.css.less`

It now works for me.

**Comment by toadkicker** [comment]
Awesome! Can we close this issue?
