### ISSUE TITLE
GlyphIcon Asset URL

### ISSUE THREAD

**Issue by jmif** [toadkicker/railsstrap#35]
Does railstrap have support for setting the GlyphIcon image asset url?  Seems that mine aren't being requested with the digest appended and I can't seem to find where to configure it.

**Comment by toadkicker** [comment]
Yes you can override the bootstrap url in `bootstrap_and_overrides.less`. The asset digest is handled in Rails 4 by `config/initializers/assets.rb`, or in Rails 3 in `config/application.rb`

**Comment by jmif** [comment]
What variable should be set for this?  Looking through the code I don't see any reference to a glyphicons path other than the standard bootstrap ones, which do not support rails asset names.  Thanks Todd!

**Comment by toadkicker** [comment]
The gem provides a [helper](https://github.com/toadkicker/railsstrap/wiki/Bages,-Labels,-and-Glyphicons) that would handle setting a hashed URL which is generated via Rails. You shouldn't need to set the URL as it is set [here](https://github.com/toadkicker/railsstrap/blob/develop/vendor/assets/bower_components/bootstrap/less/glyphicons.less) by bootstrap. 

You can copy this and override it to your liking, but you'd likely want to process `bootstrap_and_overrides.less` through ERB to pick up the asset URL. You would end up with something like:

`bootstrap_and_overrides.less.erb`:


```erb
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("<%= asset_path('glyphicons-halflings-regular.eot') %>");
  src: url("<%= asset_path('glyphicons-halflings-regular.eot?#iefix') %>") format('embedded-opentype'),
       url("<%= asset_path('glyphicons-halflings-regular.woff') %>") format('woff'),
       url('<%= asset_path('glyphicons-halflings-regular.ttf') %>') format('truetype'),
       url('<%= asset_path('glyphicons-halflings-regular.svg') %>#@{icon-font-svg-id}') format('svg');
}
```
