### ISSUE TITLE
couldn't find file 'twitter/bootstrap'

### ISSUE THREAD

**Issue by homebase-dev** [toadkicker/railsstrap#36]
Hi toadkicker,

I just tried out your gem, because I had the missing glyphicons problem with the twitter-bootstrap-rails gem, so I followed the instructions and when I run the app I got following error:

``` couldn't find file 'twitter/bootstrap' ```

![bildschirmfoto vom 2015-01-17 17 24 28](https://cloud.githubusercontent.com/assets/7480751/5789511/00679d9e-9e6e-11e4-939d-f921f776a1b5.png)

I'm using HAML, could that cause that error?
(While googleing I found this here see RobertoBarros comment https://github.com/seyhunak/twitter-bootstrap-rails/issues/91)

**Comment by homebase-dev** [comment]
I'm sorry, this error derived probably from not correctly removing the **twitter-bootstrap-rails** gem. 
After I removed the line
``` //= require twitter/bootstrap ``` from application.js and it perfectly worked.

Thanks for the great gem! :-)

**Comment by toadkicker** [comment]
Glad you like it!
