### ISSUE TITLE
Glyphicons missing on production

### ISSUE THREAD

**Issue by homebase-dev** [toadkicker/railsstrap#37]
Hi toadkicker,

when I'm in development mode, the glyphicons are there and everything works like a charm. However when I go to production mode (I prevously also did a **RAILS_ENV=production rake assets:precompile**) the glyphicons are 404 (see screenshot).

![bildschirmfoto vom 2015-01-17 20 13 58](https://cloud.githubusercontent.com/assets/7480751/5790044/6c63425a-9e87-11e4-82be-8ca9a597a6f2.png)

I noticed that there is a comment regarding fonts in the **bootstrap_and_overrides.css.less** file

```
// Glyphicons - included by default in bootstrap.
// You may need to customize config/initializers/assets.rb (Rails 4), or config/environments/[env].rb to add font paths in.
```

In my **assets.rb** I added the following:
```
Rails.application.config.assets.precompile += %w( ckeditor/* bootstrap/fonts/* fontawesome/fonts/* )
```
The assets are within the asset folder after the assets:precompile, however when the app tries to access them, it does it without the fingerprint in the name. 
E.g. ``` glyphicons-halflings-regular-917c2421bd334517fcd2892224654b37.woff ```

Maybe you can give me a hint on that one?

**Comment by toadkicker** [comment]
Use rake assets:precompile and deploy the compiled assets to your server.

**Comment by homebase-dev** [comment]
If I understand you right, than I have already done that. I did:

1. RAILS_ENV=production rake assets:precompile
2. rails s -e production

In **production.rb** I enabled: config.serve_static_assets = true, so that webrick serves me all static files. rake assets:precompile creates the assets with fingerprints, like you can see in the screenshot here:

![assets_there](https://cloud.githubusercontent.com/assets/7480751/5790816/f367f21e-9eaa-11e4-8854-d9423645c859.png)


However the app tries to access the assets without the fingerprint. Maybe thats the error?

E.g one of the files is in the assets directory under:
``` public/assets/bootstrap/fonts/glyphicons-halflings-regular-917c2421bd334517fcd2892224654b37.woff ```
The app tries to access it with
``` public/assets/bootstrap/fonts/glyphicons-halflings-regular.woff ```


If there would be a 
``` cp -p glyphicons-halflings-regular-917c2421bd334517fcd2892224654b37.woff glyphicons-halflings-regular.woff  ``` 
call for the font assets in the assets:precompile process, like for the ckeditor assets, the app would probably find it? 
I'm however not sure if this is the problem or if I have done something wrong.

**Comment by toadkicker** [comment]
Well you would usually want to use the digest version of them. Take a look at teststrap if you are on Rails 4, or [this](https://gist.github.com/samjohn/5227948) for rails 3.

**Comment by toadkicker** [comment]
Also are you using the glyph helper? this would tell rails to use the correct asset digest path if you are using it.

**Comment by toadkicker** [comment]
https://github.com/toadkicker/railsstrap/issues/35#issuecomment-70419323

**Comment by toadkicker** [comment]
@homebase-dev This will be out and fixed in the next release. You're welcome to use the development branch until then but remember it is considered unstable. Otherwise check out the diff in the PR and you can use the changes directly in your app.
