### ISSUE TITLE
tag_label support

### ISSUE THREAD

**Issue by patrickgordon** [toadkicker/railsstrap#42]
Hey mate,

Any intention to include tag_label helper/support ?

It is currently on twitter-bootstrap-rails gem:
https://github.com/seyhunak/twitter-bootstrap-rails#element-utility-helpers

Love the gem btw and that you're actively maintaining / improving it!
Cheers.

**Comment by toadkicker** [comment]
I actually removed it here out of confusion reading the badges docs: https://github.com/toadkicker/railsstrap/commit/93d95feac8cb40f7e13e5fd229d3cb84133ecaaa

Reverted commit and tagged for next release.

**Comment by Loordo** [comment]
Legend. ETA on next release?

**Comment by toadkicker** [comment]
It looks like the twbs team is skipping v 3.3.3 according to their milestones. I don't have a release date, but I'm trying to release with new helpers in each one. I would guess within ten days, but no promises.

**Comment by toadkicker** [comment]
@Loordo I've been working on some big changes. If you're interested, and I'd love for some more eyes too, on feature/refactor branch. I'm adding support for middleman and padrino, as well as full integration with active support.

**Comment by Loordo** [comment]
Cool man - I'll check this out over the weekend!

**Comment by toadkicker** [comment]
Released! I see it fixed here and if you're seeing the same please close this out, or let me know what's broken.
