### ISSUE TITLE
Glyphicons non digest path results in 404 error on Rails 4

### ISSUE THREAD

**Issue by derSascha** [toadkicker/railsstrap#45]
Hi,

the following lines result in **non-digest** glyphicon links:
https://github.com/toadkicker/railsstrap/blob/develop/vendor/assets/bower_components/bootstrap/less/glyphicons.less#L11-L19

Unfortunately, sprockets-rails does not produce non digest files in rails 4: rails/sprockets-rails/issues/49

The following results in **two** font definitions and is not a real solution...

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("<%= asset_path('glyphicons-halflings-regular.eot') %>");
  src: url("<%= asset_path('glyphicons-halflings-regular.eot?#iefix') %>") format('embedded-opentype'),
       url("<%= asset_path('glyphicons-halflings-regular.woff') %>") format('woff'),
       url('<%= asset_path('glyphicons-halflings-regular.ttf') %>') format('truetype'),
       url('<%= asset_path('glyphicons-halflings-regular.svg') %>#@{icon-font-svg-id}') format('svg');
}
```

Any suggestions how to get glyphicons working in rails 4?

Howto reproduce: Use/create a rails 4 app, clear the assets directory and precompile assets.

**Comment by derSascha** [comment]
some more infos:
I am using railsstrap in local mode and don't use the glyphicon cdn version!
```
// bootstrap_and_overrides.css.less
@import "bootstrap/less/bootstrap";
```

My current workaround looks like this:
```
# lib/tasks/assets_non_digest.rake
Rake::Task['assets:precompile'].enhance do
  Rake::Task['assets:link_non_digests'].invoke
end

namespace :assets do
  desc 'Create a non digest link on all assets.'
  task :link_non_digests => :environment do
    assets_root = File.join Rails.public_path, Rails.configuration.assets.prefix
    Sprockets::Manifest.new(assets_root).assets.each do |non_digested, with_digest|
      FileUtils.symlink(File.basename(with_digest), File.join(assets_root, non_digested), force: true)
    end
  end
end
```

**Comment by toadkicker** [comment]
As far as the font files go, they're really never going to change. You would be better served to use the CDN for the source than to force the framework to do digesting of them. There were several decent workarounds mentioned in the sprockets you linked above.

**Comment by derSascha** [comment]
I can't use the CDN version do to the fact that my application is hosted within a restricted network (without internet access). I am not sure, but why should i use this gem if can use a CDN including the css files?

Anyway, i am currently using my workaround (see above, based on the suggestions from the sprockets ticket). This works but everyone not using the CDN has the same problems with rails 4! (e.g. #35 and #37 related?) Might affect the fontawsome fonts too.

Would be nice to have a general CDN/local/assets_path option included in railsstrap.

**Comment by derSascha** [comment]
I am not a less pro but this might helpful: http://lesscss.org/features/#mixin-guards-feature

The following works great:
```
// glyphicons.less.erb
@railsstrap-glyphicons-path: "bootstrap/fonts";
@railsstrap-glyphicons-mode: CDN;

.glyphicons when(@railsstrap-glyphicons-mode = CDN) {
    @font-face {
        font-family: 'Glyphicons Halflings';
        src: font-url('some cdn...');
    }
}

.glyphicons when(@railsstrap-glyphicons-mode = custome) {
    @font-face {
        font-family: 'Glyphicons Halflings';
        src: font-url(@railsstrap-glyphicons-path '/...');
    }
}

.glyphicons when(@railsstrap-glyphicons-mode = sprockets) {
    @font-face {
        font-family: 'Glyphicons Halflings';
        src: font-url(<%= assets_path(@railsstrap-glyphicons-path '/...') %>);
    }
}

.glyphicons();
```

```
// app.less
@import "glyphicons";
@railsstrap-glyphicons-path: "special-fonts-path"; // optional: override path
@railsstrap-glyphicons-mode: sprockets; // optional: override mode
```

**Comment by toadkicker** [comment]
This would be a great addition as well. Would you like to put in a PR for it?

**Comment by toadkicker** [comment]
@derSascha In 3.3.3 I'll be providing helper methods for css/js linking and moving away from inserting all this in existing app code.

**Comment by toadkicker** [comment]
@derSascha I'm preping a v4 release and have a beta on the develop branch. It is a complete overhaul of the helper system; dropping LESS entirely from the stack in favor of SASS, and so much more. Give a try if you are still interested!
