### ISSUE TITLE
Use Bootstrap Sass instead of Less one

### ISSUE THREAD

**Issue by hauleth** [toadkicker/railsstrap#55]
Most of Rails community is using Sass/SCSS instead of Less so this gem isn't suitable in that case.

**Comment by toadkicker** [comment]
Bootstrap is not in this gem as a dependency in the gemfile. Bower provides dependency management for front end components. The reason Bower was chosen is history from when the gem broke off from twitter-bootstrap-rails' mess of having a 'static' installer option and including a completely separate version of the assets. This gem fixed that problem by removing the option and including the official builds of CSS from their respective vendor(s) that developers can include in the `application.css` manifest file.

Most dependencies distributed in Bower are LESS files. That's the reason why LESS is the preferred processor. It is true that there isn't much work Bower needs to do here. It's here as a way to have a hands-off approach to getting updates for the front end portion of the gem.

The focus at the moment is moving away from using generators and such and implementing a fork of [Bh](http://fullscreen.github.io/bh/) that includes railsstrap's custom UI components. In the `feature_refactor` branch Railsstrap provides CDN helpers for its own assets, as well as a CDN for Railsstrap itself.

This is a great question you've posed. I'm open to using SCSS but I'm not sure it will fit in or change anything for the better. What is LESS not doing for railsstrap users that using SCSS improves? How would we manage front end dependencies that are not available as gems?

**Comment by toadkicker** [comment]
@hauleth Because twbs is moving to sass in 4, we'll move there as well. I would love to see a PR for swapping less for sass files.

**Comment by toadkicker** [comment]
V4.0.0 is now fully sass and less has been dropped from Railsstrap completely
