### ISSUE TITLE
Gem::Platform::RUBY not helping with jruby?

### ISSUE THREAD

**Issue by toddh** [toadkicker/railsstrap#56]
Let me preface this with I'm not too savvy w.r.t. gemspecs.

In trying to bundle railsstrap with jruby, it doesn't appear that `Gem::Platform::RUBY` is being set to `jruby`. When I inspect the value of `Gem::Platform::RUBY` is shows up as `ruby` - even when running jruby.

On the other hand `RUBY_PLATFORM` will be assigned the value `java`.

Should this be used instead?

I've searched around, but couldn't find anything definitive. Most examples do seem to use RUBY_PLATFORM and RUBY_VERSION.

**Comment by toadkicker** [comment]
TBH I'm not a jruby user myself, but I'm happy to support a PR that adds jruby builds in travis and addresses this.

**Comment by toadkicker** [comment]
@toddh, can you [check this out?](https://travis-ci.org/toadkicker/railsstrap/jobs/76447749) any idea how jruby should be configured here for travis?

**Comment by toadkicker** [comment]
http://guides.rubygems.org/specification-reference/#platform=

**Comment by ninkibah** [comment]
I have sent you a pull request to fix this. Using my fork, I had no problem doing a bundle install, and it didn't try to install libv8, due to therubyracer.

Hope this helps.

**Comment by toadkicker** [comment]
In the next release we're not going to need therubyracer. Check out feature/refactor branch if you're interested in the future of the gem. I forked and extended https://github.com/Fullscreen/bh so we have much better integration, no more need to run an install script, cdn support, and more.

**Comment by ninkibah** [comment]
@toadkicker The bh gem looks very interesting.

**Comment by toadkicker** [comment]
Fixed in PR #58
