### ISSUE TITLE
variable @glyphiconsEotPath is undefined

### ISSUE THREAD

**Issue by LeoMustafa** [toadkicker/railsstrap#59]
I was running my app in developement on my computer,but the browser returned the message as follow:

Less::ParseError in Products#index
Showing /home/frank/rails-code/final/app/views/layouts/application.html.erb where line 15 raised:

variable @glyphiconsEotPath is undefined
Extracted source (around line 15):
13      <![endif]-->
14
15      <%= stylesheet_link_tag "application", :media => "all" %>
16
17      
18      

I tried to debug the issue in many ways,but the result always returns the same info.
Can you tell me how to solve it?

thanks

**Comment by toadkicker** [comment]
Hi @LeoMustafa! Do you have a bootstrap_and_overrides.less file? If you want to use glyphicons you need to uncomment the import statement in there. You can also set @glyphiconsEotPath to be whatever the path is to the glyphicons files should you include them in the asset pipeline.

**Comment by LeoMustafa** [comment]
I have tried it in the end, but the result is the same. I also use bootswatch and simplex theme. Will not conflict with bootstrap style? 

### This is my application.css
/*= require_self
 *= require simplex/loader
 *= require simplex/bootswatch
 *= require bootstrap_and_overrides.css.less
 */

### This is my bootstrap_and_overrides.css.less
`@font-face {
    font-family: 'Glyphicons Halflings';
    src: font-url('glyphicons-halflings-regular.eot');
    src: font-url('glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
      font-url('glyphicons-halflings-regular.woff') format('woff'),
      font-url('glyphicons-halflings-regular.ttf') format('truetype'),
      font-url('glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}`
// Glyphicons
// @import "twitter/bootstrap/glyphicons.less";

// Your custom LESS stylesheets goes here
//
// Since bootstrap was imported above you have access to its mixins which
// you may use and inherit here
//
// If you'd like to override bootstrap's own variables, you can do so here as well
// See http://twitter.github.com/bootstrap/customize.html#variables for their names and documentation

**Comment by toadkicker** [comment]
Hm the current release has a different setup for this:

```
/*
 Bootstrap
 This line imports bootstrap, modified to use glyphicons from Cloudflare CDN.
*/
@import "bootstrap";

/*
 Glyphicons - included by default in bootstrap.
 If for any reason you prefer to have them as part of the asset pipeline, uncomment this.
 If you choose to use this, open config/initializers/assets.rb (rails 4) and add this line:
 Rails.application.config.assets.precompile += %w( *.eot *.woff *.ttf *.svg )
*/

// @import "glyphicons";

/*
  FontAwesome is hosted via CDN as well. If you prefer to have them included in the asset
  pipeline, comment this out and see the next section.
*/
@import 'fontawesome';

/*
 Font Awesome
 If for some reason you want fontawesome as part of the asset pipeline, comment out
 the above refererence and uncomment the following lines. If you choose to use this, open
 config/initializers/assets.rb (rails 4) and add this line:
 Rails.application.config.assets.precompile += %w( *.eot *.woff *.ttf *.svg )
*/

//@import 'fontawesome-local';

//If you want exotic placement features, animations, and more, import this:
@import "railsstrap";

/*
 Date and Time Picker (https://github.com/toadkicker/railsstrap/wiki/Date-and-Time-Picker)
 To enable the date and time picker, uncomment this line:
 Don't forget to include the javascript library as well.
*/

//@import "datepicker/datepicker";

```

**Comment by toadkicker** [comment]
If you run the install generator do you get different files than what is in your project now?

**Comment by LeoMustafa** [comment]
I have solved this issue, the reason is that i used the lastest twitter-bootstrap-rails gem, but when i use
twitter-bootstrap-rails 3.2.0 it seems to be fine.
Do you think that is a bug in advanced versions?

thanks

**Comment by toadkicker** [comment]
Railsstrap is not compatible with twitter-bootstrap-rails gem.

**Comment by LeoMustafa** [comment]
OK! I will try to use Railsstrap in my app or project in the future.

**Comment by toadkicker** [comment]
Hello it's been a while so I'm going to go ahead and close this. If you're interested in helping out V4 is coming soon and I would love for you to check it out!
